project:
  type: website
  output-dir: docs

website:
  title: "Arantza Lira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutme.qmd
      - projects.qmd
      - resume.qmd
      - hobbies.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

